### ISSUE TITLE
tutorial [.py -> .rst]

### ISSUE THREAD

**Issue by the872** [pavanramkumar/pyglmnet#110]
since the tutorial is not being compiled would it make sense to convert it into a .rst file so it is not nested (tutorials/tutorial vs just tutorial) in the [docs site](http://pavanramkumar.github.io/pyglmnet/)? 
 
just not sure what is wanted out of the tutorial for future implementations

**Comment by pavanramkumar** [comment]
Hey @the872 I agree that it can be converted to rst. I envision it more as a walk through the math with small blocks of code to aid future developers understand our class.

Shall I give you push access to my `clean_docs` branch? If you can port from `.py` to `.rst` I can then go through and modify content.

**Comment by the872** [comment]
@pavanramkumar sure thing!

**Comment by pavanramkumar** [comment]
great, i gave you collaborator access to the repo. once you're done porting to `tutorial.rst`, you can push directly to the `cleaning_docs` branch. it should automatically update PR #109 

i can then update content.

**Comment by pavanramkumar** [comment]
once you commit locally, do:
```
git push origin <your-local-branch>:cleaning_docs
```

**Comment by the872** [comment]
@pavanramkumar your commits aren't showing in the [cleaning_docs](https://github.com/pavanramkumar/pyglmnet/tree/cleaning_docs) branch. maybe recommit them from local? otherwise, this particular issue should be wrapped up! will follow up to restructure the conf.py and index.rst to include the tutorial

**Comment by pavanramkumar** [comment]
@the872 i deleted the cleaning_docs branch. 

can you now submit PR with `tutorial.rst` along with `index.rst` and `conf.py` updates from your own fork? sorry for the double work, but this way is safer :)

P.S. i'll be gone for a week, but others can merge your PRs as needed
