### ISSUE TITLE
cpd example is breaking

### ISSUE THREAD

**Issue by the872** [pavanramkumar/pyglmnet#114]
[this example](http://pavanramkumar.github.io/pyglmnet/auto_examples/api/plot_poisson_2.html#sphx-glr-auto-examples-api-plot-poisson-2-py) is breaking on the site but when I run the docs locally it seems fine

**Comment by jasmainak** [comment]
let me try to run it ...

**Comment by jasmainak** [comment]
I get the following error when I try to build the examples:

```
../examples/api/plot_poisson_2.py is not compiling:
Traceback (most recent call last):
  File "/home/mainak/anaconda2/lib/python2.7/site-packages/sphinx_gallery-0.1.2-py2.7.egg/sphinx_gallery/gen_rst.py", line 467, in execute_script
    exec(code_block, example_globals)
  File "<string>", line 2, in <module>
AttributeError: 'GLM' object has no attribute '_grad_L2loss'
```
Do you want to try fixing it?

**Comment by jasmainak** [comment]
never mind, it was a problem with my setup. It's fixed now. Closing issue ...
