### ISSUE TITLE
Make family names consistent with R package or statsmodels

### ISSUE THREAD

**Issue by ravigarg27** [pavanramkumar/pyglmnet#125]
The R version has Gaussian as family/distribution name.

**Comment by ravigarg27** [comment]
The default parameters can also be changed to make it similar to the R package

**Comment by jasmainak** [comment]
PR welcome :)

**Comment by pavanramkumar** [comment]
I also want to rename `poisson` to `poisson-softplus` and `poissonexp` to `poisson`. This will likely break a few examples, so it's important to go through all of the docs and fix them.

**Comment by jasmainak** [comment]
sounds good
