### ISSUE TITLE
Tikhonov regularizer

### ISSUE THREAD

**Issue by pavanramkumar** [pavanramkumar/pyglmnet#139]
[Tikonov regularization](https://en.wikipedia.org/wiki/Tikhonov_regularization) is really useful for problems where we know that features covary with each other.

For instance, in time series problems, nearby time points are correlated. In receptive-field estimation problems, nearby pixels are correlated. In gene expression problems, we have prior knowledge on which genes are likely to be co-expressed.

One way to implement this is to accept a parameter called `Tikhonov_Tau` which is a `n_features` x `n_features` matrix.

We would then pass this parameter to the `_penalty` function, where instead of 

```
penalty = reg_lambda * (1.0 - alpha) * 0.5 * np.linalg.norm(beta, 2) + \
                alpha * np.linalg.norm(beta, 1)
```

we would write 

```
L2penalty = reg_lambda * (1.0 - alpha) * 0.5 * np.dot(np.dot(beta.T, Tiknonov_Tau), beta) + \
                   alpha * np.linalg.norm(beta, 1)
```

**Comment by jasmainak** [comment]
+1, sounds easy enough to implement.
