### ISSUE TITLE
cheatsheet as part of documentation?

### ISSUE THREAD

**Issue by jasmainak** [pavanramkumar/pyglmnet#147]
I love this cheat sheet but I fear that updating this is going to be a pain. Every time you update it, the whole pdf will show up in the diff. That's not good for the repo as the history keeps getting larger. So, it takes longer and longer for people to clone ... 

Also, I feel it's less accessible when it's there as a pdf than a webpage. If we can make it part of the docs, that would be great. Thoughts?

**Comment by jasmainak** [comment]
Also, if it's in sphinx you can crossref the rows to their relevant function documentation ...

**Comment by pavanramkumar** [comment]
Agreed, I'm just must faster in latex than sphinx. Anyone want to translate this?
