### ISSUE TITLE
coveralls -> codecov

### ISSUE THREAD

**Issue by jasmainak** [pavanramkumar/pyglmnet#161]
The analytics provided by these guys are much better: https://codecov.io/

You can see a diff with which lines lost test coverage and which lines gained test coverage etc.

**Comment by pavanramkumar** [comment]
solved by af6162f60fb5329559e3c358c3501afeddb2c4e2 and 1c719b99b7a0951b2737c11a63ad79809f0173c7 but the badge is not displaying the coverage percentage.

**Comment by pavanramkumar** [comment]
solved by f60435b4a7f32fc380041ea7d8e2f045821bb091
