### ISSUE TITLE
verbose true does not print output

### ISSUE THREAD

**Issue by titipata** [pavanramkumar/pyglmnet#17]
When I set `verbose=True` when I created GLM model and train. It does not print out the output.

**Comment by jasmainak** [comment]
I noticed that a bunch of print statements were being used for verbosity. There happens to be a package to take care of the verbosity levels: https://docs.python.org/2/library/logging.html.

**Comment by titipata** [comment]
@jasmainak, Ah, I see! I'm not quite pro in doing logging output. Do you want to implement these output/logging?

**Comment by jasmainak** [comment]
okay, I'll take care of it :)

**Comment by titipata** [comment]
@jasmainak, note that I have one bug in my recent pull-request (in `penalty` function). Maybe you would like to fix that fist before setup.

**Comment by jasmainak** [comment]
your bug should be fixed here: https://github.com/pavanramkumar/pyglmnet/pull/19

**Comment by pavanramkumar** [comment]
looks like this is done now! shall i close the issue?

**Comment by titipata** [comment]
yes, you can close this issue!
