### ISSUE TITLE
more flexible with y input format

### ISSUE THREAD

**Issue by hugoguh** [pavanramkumar/pyglmnet#24]
for poisson and binomial and normal  i get an error if y isn't a 2d n-by-1 array. should allow a one dimensional array.
e.g.:
`X, y = make_classification(n_samples=10000, n_classes=2, 
                           n_informative=100, n_features=100, n_redundant=0)`
`model = GLM(distr='binomial', verbose=False, alpha=0.05, 
            max_iter=1000, learning_rate=1e-4, 
            reg_lambda=[0])`
`model.fit(X, np.transpose(np.atleast_2d(y)))`

shouldn’t give an error when input `model.fit(X, y)`, make the transformation inside

**Comment by titipata** [comment]
Got it, I will solve this issue.

**Comment by titipata** [comment]
This should partially solve by https://github.com/pavanramkumar/pyglmnet/pull/27.

**Comment by pavanramkumar** [comment]
#27 is acceptable fix
