### ISSUE TITLE
"The version specified ('unstable' ) is an invalid version..."

### ISSUE THREAD

**Issue by tcyb** [pavanramkumar/pyglmnet#30]
Just a heads up, setuptools complained when I tried to execute setup.py:

> C:\Users\Ted\Anaconda\lib\site-packages\setuptools-20.3-py2.7.egg\setuptools\dist.py:294: UserWarning: The version specified ('unstable') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.

Setup still seems to have gone fine (still running basic tests), but figured I'd give you a heads up anyway. [PEP 440](https://www.python.org/dev/peps/pep-0440/) says that it supports dev branch and pre-release versioning, so maybe that might be suitable for this stage of the code?

**Comment by titipata** [comment]
@tcyb, if you change `VERSION = 'unstable'` to says `0.1` and use `setup.py` to install. Will it still report this error?

@jasmainak, any suggestion on this?

**Comment by jasmainak** [comment]
maybe we can replace it with `'0.1.dev0'`. That might be more appropriate I think.

**Comment by pavanramkumar** [comment]
done!
