### ISSUE TITLE
Move away from ipynb demos to sphinx gallery for tutorials

### ISSUE THREAD

**Issue by pavanramkumar** [pavanramkumar/pyglmnet#33]
http://sphinx-gallery.readthedocs.io/en/latest/tutorials/plot_notebook.html#sphx-glr-tutorials-plot-notebook-py

**Comment by pavanramkumar** [comment]
I would vote to do this a little later, since we're still developing and testing stuff on the notebooks.

**Comment by jasmainak** [comment]
is it possible to do the testing on the notebooks separately? Basically you can host it as another repo (`pyglmnet-notebooks`?) The immediate concern I have is that the history once it gets cluttered cannot be fixed ... at least not after the first release

**Comment by pavanramkumar** [comment]
@jasmainak @titipata you can continue sphinx conversation here
