### ISSUE TITLE
stylistic changes

### ISSUE THREAD

**Issue by jasmainak** [pavanramkumar/pyglmnet#35]
some simple stylistic suggestions:

* For estimated parameters, follow the variable name with underscore. E.g., `model.beta_`. This is the convention in scikit-learn.
* For shape of matrices, prefix it with `n_`. E.g., `n_features` or `n_samples` etc.
* For looping, you could use `idx` and then use a prefix to indicate what you're looping over. E.g., `l_idx`. It immediately tells you that it's the looping variable.
* In the same spirit, avoid single letter variable names. It's slightly cryptic. Exceptions to this rule are `X` and `y` which are universally known as data and labels respectively.
* replace `[]` and `{}` by `list()` and `dict()` respectively because it's hard to tell the difference between `[]` and `{}`. Same spirit, it's very hard to tell the difference between `1` and `l` -- easy to confuse.
* flake8 / pep8 conventions: use lower-case for variable names, camel case for function names and lower case for function/method names. E.g., `n_features`, `AwesomeClass` and `awesome_method`. I think it's okay to break this rule sometimes (e.g., `L1` and `L2` is cool), but generally it's a nice rule of thumb.

hopefully it makes the code more readable :)

**Comment by pavanramkumar** [comment]
@jasmainak super useful! have reflected many of these changes now. close issue?

**Comment by jasmainak** [comment]
excellent! It's more of a checklist for the future :) feel free to close it
