### ISSUE TITLE
fit_  instead of fit_params in README

### ISSUE THREAD

**Issue by hugoguh** [pavanramkumar/pyglmnet#45]
notebook also has the same bug

**Comment by hugoguh** [comment]
I guess this means add readme code and notebook code to tests?

**Comment by pavanramkumar** [comment]
good idea to automate tests for notebooks. i guess this will be a lot easier when we move the tutorials to sphinx gallery using `.py` files instead of `.iypnb`. we can simply include a copy of these tutorial files inside `tests/`

**Comment by jasmainak** [comment]
note one thing about tests. They should ideally be really quick so that Travis CI doesn't take forever to become green. Ideally, we should never go above a couple of minutes (but that's being optimistic :)

**Comment by hugoguh** [comment]
how about having more than one version of tests then. we could have one that does more extensive test though takes longer

**Comment by jasmainak** [comment]
this is indeed what is usually done in many python packages :) `nose` also allows you to do doctests. I think that might address your issue.
