### ISSUE TITLE
make methods / functions private

### ISSUE THREAD

**Issue by jasmainak** [pavanramkumar/pyglmnet#50]
Any method / function which should not be user accessible should be made private. Private functions can be removed / restructured without needing a deprecation cycle.

**Comment by jasmainak** [comment]
After some thinking, I feel the following methods should be the only ones public:
* `fit`
* `predict`
* `fit_predict`
* `score`
* `copy`
* `get_params`

And the following magic methods:
* `__repr__`
* `__init__`. 

The rest should all be private.

**Comment by pavanramkumar** [comment]
this is fixed now by PR #107
