### ISSUE TITLE
error in Notes inside pyglmnet.py 

### ISSUE THREAD

**Issue by hugoguh** [pavanramkumar/pyglmnet#52]
in pyglmnet.py `glm[2].predict(X_test)` instead of `glm[2].predict(X_test, y_test)`
```python
Notes
    -----
    To select subset of fitted glm models, you can simply do:
    >>> glm = glm[1:3]
    >>> glm[2].predict(X_test, y_test)
    “"”
```

**Comment by jasmainak** [comment]
Fixed by https://github.com/pavanramkumar/pyglmnet/commit/21baa562ff81a19d8bb7f7928b5b6f50fac3b511
