### ISSUE TITLE
still bug in README

### ISSUE THREAD

**Issue by hugoguh** [pavanramkumar/pyglmnet#53]
`yhat = model.predict(scaler.transform(Xt), fit_param)`

gives an error. should be:
`yhat = model.predict(scaler.transform(Xt))`

also why does it print the same thing several times when you run `mode.fit`?

**Comment by hugoguh** [comment]
there really should be a way of testing the readme code (and the example notebook) every time there is a change that might affect it

**Comment by jasmainak** [comment]
unfortunately there really isn't a way to test it if you put examples in README.md :\ I can switch to sphinx if you want. That's what all serious python projects use for their documentation.

That way, you can run the examples in continuous integration but I would need help in transforming the examples to sphinx. It's a lot of copy-pasting ...

**Comment by titipata** [comment]
@jasmainak It would be great if you start sphinx document folder. I can handle it afterward. I don't know how to custom [sphinx style](http://sphinx-gallery.readthedocs.io/en/latest/tutorials/plot_notebook.html#sphx-glr-tutorials-plot-notebook-py).

**Comment by pavanramkumar** [comment]
this bug is fixed by commit 9c53b9c56c477d70df81a2f82d70e5268e127c98

**Comment by pavanramkumar** [comment]
let's move sphinx discussion to the sphinx issue #33
