### ISSUE TITLE
verbose

### ISSUE THREAD

**Issue by hugoguh** [pavanramkumar/pyglmnet#55]
shouldn’t verbose be allowed to be set to `False` or `True` after the model has been instantiated?
shouldn’t it be a option of the `.fit` method?

**Comment by titipata** [comment]
I think this should stated when you create class as we have right now.

**Comment by hugoguh** [comment]
I agree but maybe the user should be allowed to change it:
`model.verbose = False`

like we can do `alpha` for instance:
`model.alpha = 0.9`

btw also should allow
`model.reg_lambda = 0.1`. It gives an error unless we do `model.reg_lambda=[0.1]`

**Comment by titipata** [comment]
I guess, they can do it already right?

**Comment by hugoguh** [comment]
they can do `model.verbose = False` but it doesn’t do anything, it doesn’t stop verbose next time you run `.fit`

**Comment by jasmainak** [comment]
you need to use a decorator and a verbose argument to the functions. Probably not worth the extra lines of code? for now, you can simply use `set_log_level` directly?

**Comment by pavanramkumar** [comment]
@hugoguh would recommend that this is not needed. it's an extremely rare use case that models fit using the same object with `verbose=True` would need to be fit again with `verbose=False`. We need to design for 90% of the most common use cases.

closing this issue to keep things manageable.
