### ISSUE TITLE
weird effect in verbose

### ISSUE THREAD

**Issue by hugoguh** [pavanramkumar/pyglmnet#56]
if I instantiate the same model again, the verbose adds one repetition:
![screen shot 2016-05-08 at 1 39 53 pm](https://cloud.githubusercontent.com/assets/3664942/15099717/8c613248-1522-11e6-907a-5e454716bc90.png)

it adds one more every time I instantiate a model. Doesn’t even have to be the same model again.

**Comment by jasmainak** [comment]
hmm ... can you share a few lines of code to reproduce the problem?

**Comment by hugoguh** [comment]
sure!
let’s see it with only one `reg_lambda`, first just like in README, except setting one `reg_lambda`:

```python
import numpy as np
import scipy.sparse as sps
from sklearn.preprocessing import StandardScaler
from pyglmnet import GLM

# create class of Generalized Linear model
model = GLM(distr='poisson', verbose=True, alpha=0.05, reg_lambda = 0.1)

n_samples, n_features = 10000, 100

# coefficients
beta0 = np.random.normal(0.0, 1.0, 1)
beta = sps.rand(n_features, 1, 0.1)
beta = np.array(beta.todense())

# training data
Xr = np.random.normal(0.0, 1.0, [n_samples, n_features])
yr = model.simulate(beta0, beta, Xr)

# testing data
Xt = np.random.normal(0.0, 1.0, [n_samples, n_features])
yt = model.simulate(beta0, beta, Xt)

# fit Generalized Linear Model
scaler = StandardScaler().fit(Xr)
```

now fit
```python
model.fit(scaler.transform(Xr), yr)
```
here’s the output, looks good except for that extra space ;):
![screen shot 2016-05-09 at 11 02 30 am](https://cloud.githubusercontent.com/assets/3664942/15119239/9a556500-15d5-11e6-9f10-7da3b55d680a.png)

now instantiate another (or re-instantiate same model):
```python
model_another = GLM(distr='poisson', verbose=True, alpha=0.05, reg_lambda = 0.1)
```
now fit either model:
```python
model.fit(scaler.transform(Xr), yr)
```
here’s the output, it repeats everything twice:
![screen shot 2016-05-09 at 11 06 25 am](https://cloud.githubusercontent.com/assets/3664942/15119347/1aab3e96-15d6-11e6-9747-01ef981b06e2.png)

looks like the number of repetitions equals the number of models you have instantiated so far

**Comment by hugoguh** [comment]
remove that extra spacing after `dL/L:...` also :)
