### ISSUE TITLE
score for all the reg_lambdas?

### ISSUE THREAD

**Issue by hugoguh** [pavanramkumar/pyglmnet#58]
wouldn’t it be nice if `model.deviance(yt,model.fit(Xr, yr).predict(Xt))` worked for more than one `reg_lambda`?
i.e computed the deviance for each the `yt_hat` in the output of `model.fit(Xr, yr).predict(Xt)` (one for each reg_lambdas)

**Comment by jasmainak** [comment]
I agree this would be nice to have :)

**Comment by pavanramkumar** [comment]
@hugoguh want to implement this by following same approach as @jasmainak used in the `predict()` method:

``` python
if isinstance(self.fit_, list):
    yhat = list()
    for fit in self.fit_:
        yhat.append(self.lmb(fit['beta0'], fit['beta'], X))
else:
        yhat = self.lmb(self.fit_['beta0'], self.fit_['beta'], X)
return np.asarray(yhat)
```

**Comment by pavanramkumar** [comment]
@hugoguh instead of `self.fit_` you would check if `yhat` is a list

**Comment by hugoguh** [comment]
ok, will do the same for pseudoR2 right?

**Comment by pavanramkumar** [comment]
sure, already assigned :)

would be the same implementation for both `deviance()` and `pseudo_R2()`. 

my suggestion: abstract these away with a method called `score()`. could work something like:
```python
model.score(yt, model.fit(Xr, yr).predict(Xt), method='deviance')
```

where ```score()``` would call ```deviance()``` and ```pseudo_R2```:

```python
def score(self, y, yhat, ynull, method):
    if(method == 'deviance'):
        s = self.deviance(self, y, yhat)
    elif(method =='pseudo_R2'):
        s = self.pseudo_R2(self, y, yhat, ynull)
```

This way you can leave the current ```deviance``` and ```pseudo_R2``` functions as they are simply modify ```score``` to return a list if ```yhat``` is a list.

**Comment by jasmainak** [comment]
I like the idea of a `score` method. It's also consistent with `scikit-learn` API. So, you should be able to use `cross_val_score` ...

**Comment by pavanramkumar** [comment]
can we close this if we solve #98 ?

**Comment by jasmainak** [comment]
yes!
