### ISSUE TITLE
copy a model

### ISSUE THREAD

**Issue by hugoguh** [pavanramkumar/pyglmnet#59]
why does it only let me do this:
`model_another = model[:]` after i run `model.fit` once?

If there another way of instantiating a new model from an existing one?

**Comment by hugoguh** [comment]
related issue: it should delete the `.fit_` if the user changes `.alpha`,  `.reg_lambda` or `distribution` of a model

**Comment by jasmainak** [comment]
I didn't want to allow slicing the `beta` unless you have run `fit` because `beta` does not exist yet. We could add a `copy` method which calls `deepcopy.copy` and returns a copy of your model. I can do it after work today. It's pretty easy

**Comment by jasmainak** [comment]
Regarding your second comment, I think we shouldn't allow the user to change `.alpha` etc. One way to enforce that is to have these parameters as private variables and then return `.alpha` using the `@property` decorator. I can take care of this one too

**Comment by pavanramkumar** [comment]
in the interest of simplicity i would recommend not having the ability to access `alpha` or `lambda`. reason: very rare use case that user both sets the `alpha` and `lambda` while instantiating the model and also wants to read it back from the model

**Comment by pavanramkumar** [comment]
i'll close this issue
