### ISSUE TITLE
Investigate instructions in the shablona project to produce PyPI package

### ISSUE THREAD

**Issue by pavanramkumar** [pavanramkumar/pyglmnet#6]
Shablona:
https://github.com/uwescience/shablona

More here:
http://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/

**Comment by jasmainak** [comment]
I think the most important thing is the tests. You can check out pytest or nosetests for that. It's to ensure that a new pull request doesn't break the code. Then you can add continuous integration of your tests with Travis, but that's not super-critical as you can run it locally as well.

**Comment by pavanramkumar** [comment]
This is done. I'll create a separate issue for creating a PyPI package that's downloadable with pip

**Comment by jasmainak** [comment]
We could make a milestone on github for the first release and mark issues
using the milestone :)

Note that changing the API after you release would require a deprecation
cycle

**Comment by pavanramkumar** [comment]
Just made a milestone :) 

Ok, noted.

- Ideally, the APIs should not change after the first stable release. For instance, a new method can be introduced for the SGD variant: `fit_sgd()` 
- Internal algorithmic changes shouldn't change the API:
