### ISSUE TITLE
shape issue in poissonexp output

### ISSUE THREAD

**Issue by hugoguh** [pavanramkumar/pyglmnet#70]
running README example, `.predict` has output with shape `(10, 10000, 1)` when using `distr=poissonexp`
for the other distributions has shape `(10, 1000)`

**Comment by pavanramkumar** [comment]
related: tests can be improved by adding shape checks for key outputs

**Comment by jasmainak** [comment]
> related: tests can be improved by adding shape checks for key outputs

+10 :) I think we should loop over all the different distributions and check for some common stuff -- like shape etc.

**Comment by pavanramkumar** [comment]
@jasmainak assigned you the shape issues, feel free to say no :)

**Comment by hugoguh** [comment]
cool but tomorrow morning :)
