### ISSUE TITLE
inherit `scikit-learn` BaseEstimator object?

### ISSUE THREAD

**Issue by jasmainak** [pavanramkumar/pyglmnet#72]
We can copy the `BaseEstimator` class from here (with proper attribution): https://github.com/mne-tools/mne-python/blob/master/mne/decoding/base.py

Then it should work with `scikit-learn` cv objects without having a dependency.

**Comment by pavanramkumar** [comment]
@jasmainak is this related to `cvpyglmnet` issue? should we merge the issues or classify this as `version 0.2`?

**Comment by jasmainak** [comment]
I can look into it early next week if nobody beats me to it :) It's not too difficult. I suppose it would be neat if you can show cross-validation results with the `GLM` object before the release. My idea is that for the first release, we can first show the simple use case where you can do cross-validation with a `scikit-learn` cv object. The `cvpyglmnet` object that you first proposed might be handy if you want to do grid-search with warm-starts -- doing it more efficiently than with `scikit-learn`. Since the details are not super clear in my (or anyone else's) head yet, I suggested waiting before we proceed in that direction ...

**Comment by titipata** [comment]
@pavanramkumar I totally agree with @jasmainak. If we inherit `BaseEstimator`, it will look very clean and later on we can easily apply cross validation from `scikit-learn`. +1 for this

**Comment by daniel-acuna** [comment]
@jasmainak I can work on this if you want

**Comment by daniel-acuna** [comment]
@jasmainak @pavanramkumar following the idea of using sklearn's classes, I was wondering if I should inherit from the `ElasticNetCV` class in https://github.com/scikit-learn/scikit-learn/blob/5876f885f04f1abbf46a9cdfb5cb1d5a2ff64f98/sklearn/linear_model/coordinate_descent.py#L1355 I would only need to redefine the function that produces the path (https://github.com/scikit-learn/scikit-learn/blob/5876f885f04f1abbf46a9cdfb5cb1d5a2ff64f98/sklearn/linear_model/coordinate_descent.py#L1511) and `sklearn` would do the rest.

**Comment by jasmainak** [comment]
> @jasmainak @pavanramkumar following the idea of using sklearn's classes, I was wondering if I should inherit from the ElasticNetCV class

what is the least "copy-able" unit if we were to not create a dependency? 

Actually I just realized this, the license for `scikit-learn` is BSD whereas ours is MIT. @pavanramkumar any particular reason for going with MIT? we would have to copy the BSD license clause in our LICENSE file just for the `scikit-learn` parts. Something like this : https://github.com/nilearn/nilearn/blob/master/LICENSE. Or if we switch to BSD, then I think one license file will do it.

**Comment by jasmainak** [comment]
> @jasmainak I can work on this if you want

that's perfect! Feel free to make a "WIP" even before you have something that works perfectly. You can continue working on it by pushing to the same branch. It's always a good idea for everyone to look at the code early in the development path :)

**Comment by daniel-acuna** [comment]
@jasmainak The thing is that ElasticNetCV does the cross validation in a special way by understanding that there is warm start during the regularization path. The simplest inheretance would need to come from `BaseEstimator` and `RegressorMixin` (or `ClassifierMixin` for logistic and multinomial regression, not sure yet) I'll work on it as WIP

**Comment by jasmainak** [comment]
okay I see. I think it might be specially geared for their `Lasso` object but I'm not sure ... 

Also, if we have a `scikit-learn` import in our `pyglmnet.py` file, then we introduce a dependency on `scikit-learn`. Whereas copying the relevant parts of the code will ensure compatibility without introducing dependence. I'm not sure which is better ... I'll look at your `WIP` code :)

**Comment by pavanramkumar** [comment]
@daniel-acuna do remember that inheriting two classes vs. writing your own class while conforming to API and style elements is probably equivalent in terms of effort!

**Comment by daniel-acuna** [comment]
@pavanramkumar If I inherit from sklearn classes then I can be used in all data analysis pipelines that sklearn has. Also, people will know better what our class is supposed to do

**Comment by pavanramkumar** [comment]
@daniel-acuna sure, agreed

**Comment by jasmainak** [comment]
@daniel-acuna let's see what your PR means in terms of code changes. We can continue the discussion once you make the PR :)

**Comment by pavanramkumar** [comment]
@jasmainak happy to go with BSD license. 

apparently BSD license is for those who fear their name will be dragged through the mud, whereas MIT license is for those who fear their contributions will never be used :)

http://programmers.stackexchange.com/questions/82321/why-do-people-pick-the-mit-license-over-bsd-if-bsds-non-endorsement-clause-i

**Comment by jasmainak** [comment]
bah, I don't know the real difference between the two :\ BSD is used everywhere because it even allows commercial use -- maximum impact :) not sure if MIT allows that but MIT and BSD are pretty similar as far as I know. If most people are using BSD, it might be easier in terms of logistics I suppose?

**Comment by daniel-acuna** [comment]
@jasmainak At the end, I don't use `scikit-learn` code in the new PR #78

**Comment by jasmainak** [comment]
very cool @daniel-acuna !
