### ISSUE TITLE
add API reference

### ISSUE THREAD

**Issue by jasmainak** [pavanramkumar/pyglmnet#74]
more like a reminder for me. Something like this: http://sphinx-gallery.readthedocs.io/en/latest/reference.html. It will list all the functions + docstrings in the html pages.

but @titipata feel free to add it with your PR if you're in the flow :)

**Comment by jasmainak** [comment]
@pavanramkumar hope I am not adding too many issues! just trying to check of things which are necessary to make it look polished :)

**Comment by pavanramkumar** [comment]
@jasmainak no, your suggestions and contributions are amazing! but i'll continue to be issue nazi to make sure we don't get distracted...

**Comment by titipata** [comment]
I add API documentation in https://github.com/pavanramkumar/pyglmnet/pull/87, please feel free to take a look.
