### ISSUE TITLE
gh-pages does not render css files

### ISSUE THREAD

**Issue by titipata** [pavanramkumar/pyglmnet#77]
This issue is for me to solve. If anyone knows how to solve, feel free to help.

@jasmainak @pavanramkumar , I put generated documentation to `gh-pages` branch which you can see at http://pavanramkumar.github.io/pyglmnet/. However, the page doesn't render css file (I'm not sure why). Here is snippet on how I push it branch.

```bash
SOURCES="doc examples"
git checkout gh-pages
rm -rf *
git checkout master $SOURCES
cd doc/
make html
mv -fv _build/html/* ../
cd ..
rm -rf doc
git add -A
git commit -m "Documentation build from [SHA]"
git push origin gh-pages
git checkout master
```

see reference [here](http://blog.nikhilism.com/2012/08/automatic-github-pages-generation-from.html) and [here](https://github.com/vmlaker/pythonwildmagic/blob/master/doc/create-gh-pages.sh)

**Comment by jasmainak** [comment]
@titipata can you see how `nilearn` does it: http://nilearn.github.io/ ?

**Comment by titipata** [comment]
@jasmainak thanks! I will explore how they do it.

**Comment by pavanramkumar** [comment]
@jasmainak help please! @titipata has been trying to solve this but we're not able to figure out how style/css works

**Comment by titipata** [comment]
@bluenex investigated but still cannot find why it doesn't load css. He tried putting css file directly on master branch but doesn't work.

**Comment by jasmainak** [comment]
are you sure you looked carefully what `nilearn` was doing? ;)

it's fixed now :)

**Comment by titipata** [comment]
Oh my goodness, that's like one file!

**Comment by jasmainak** [comment]
next step is to add integration of the docs with circle-ci :)

**Comment by pavanramkumar** [comment]
very cool @jasmainak @titipata @bluenex !!
