### ISSUE TITLE
setup.py develop install not working

### ISSUE THREAD

**Issue by jasmainak** [pavanramkumar/pyglmnet#89]
Not sure why this is the case ... but I am having to run the install command every time I change everything

**Comment by pavanramkumar** [comment]
yes, both @titipata  and myself face the same issue. i currently rerun setup.py after each change to my code.

**Comment by pavanramkumar** [comment]
so, no need to run `python setup.py develop install` each time we make a change?

**Comment by jasmainak** [comment]
yeah, but you would still need to exit `ipython` and enter it again ...

That's why I work with `nosetests --pdb` because I don't need to exit `ipython`
