### ISSUE TITLE
relative paths in documentation

### ISSUE THREAD

**Issue by pavanramkumar** [pavanramkumar/pyglmnet#99]
use relative paths that are robust to new host for documentation, e.g.
`pavanramkumar.github.io/pyglmnet/auto_examples/plot_poisson.html` -->
`auto_examples/plot_poisson.html`

**Comment by the872** [comment]
@pavanramkumar doesn't gitpages take care of this?

**Comment by the872** [comment]
also if someone could do a pull request on the gh-pages branch that would be helpful

**Comment by jasmainak** [comment]
@the872 we use `make install` to push to the `gh-pages` -- no pull request. It's easier to manage that way.

**Comment by titipata** [comment]
@pavanramkumar, relative path is taking care of in Sphinx (as @the872 replied). @the872 yeah, we take care of `make install` directly. So you can submit any changes in `master` branch and we'll run `make install` for you.

**Comment by pavanramkumar** [comment]
ok, thanks @titpata @the872. @jasmainak what exactly did you mean by relative paths? only in `README.md`?

as @titipata said, you can submit PR to `master` and we can run `make installl` after merge

**Comment by jasmainak** [comment]
my bad, since this page isn't built by sphinx, relative paths won't help. But we should keep this in mind in general.
